project_id = "motdnvzwtofailxjlhfg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
api_port = 54325

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54327
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_nonce = true

[edge-runtime]
enabled = true
port = 54328

[[edge-runtime.functions]]
name = "openai-ocr"
verify_jwt = false


[[edge-runtime.functions]]
name = "test-openai-vision"
verify_jwt = false

[[edge-runtime.functions]]
name = "preprocess-knowledge"
verify_jwt = false

[analytics]
enabled = false